### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by ChiSerkan** [DarkIntaqt/challenges#256]
Source: https://challenges.darkintaqt.com/tr/Maximus-x07/history

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

{"componentStack":"
    at k (https://challenges.darkintaqt.com/static/js/628.0f1b7537.chunk.js:1:10280)
    at n (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:320488)
    at gt (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:79219)
    at Ot (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:82533)
    at div
    at Kn (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:110108)
    at ei (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:112901)
    at r (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:551474)
    at si (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:133779)
    at gt (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:79219)
    at kt (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:81849)
    at div
    at dn (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:92700)
    at gt (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:79219)
    at Ot (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:82533)
    at i (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:151611)
    at vi (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:149944)
    at Ct (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:81908)
    at Rt (https://challenges.darkintaqt.com/static/js/main.7793108b.js:2:84104)"}

**Comment by DarkIntaqt** [comment]
Sorry for the inconvenience. Should I verify you manually?

**Comment by ChiSerkan** [comment]
That'd be great, thanks.

**Comment by DarkIntaqt** [comment]
I verified you and I believe I fixed the bug as well. Have fun!
